services:
    api:
        build:
            context: ./
            dockerfile: cmd/api/Dockerfile
        image: ${REPO}/api:${TAG}
        restart: unless-stopped
        tty: true
        ports:
            - ${PORT}:${PORT}
        env_file:
            - .env
        dns:
            - 8.8.8.8
            - 8.8.4.4
        volumes:
            - /etc/localtime:/etc/localtime:ro # Set docker time
        networks:
          - music-service
    mongodb:
        image: mongo:7
        container_name: mongodb_music
        restart: always
        ports:
            - 27117:27017
        volumes:
            - ./mongo_data:/data/db
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=root
        networks:
          - music-service
        #rabbitmq
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        restart: always
        environment:
            - RABBITMQ_DEFAULT_USER=test
            - RABBITMQ_DEFAULT_PASS=test
            - RABBITMQ_DEFAULT_VHOST=test_queue
        ports:
            - 5672:5672
            - 15672:15672
        networks:
            - music-service

# # Docker Network
networks:
    music-service:
        driver: bridge

volumes:
  mongo_data:
      driver: local
