// Code generated by mockery v2.28.1. DO NOT EDIT.

package jwt

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockMaker is an autogenerated mock type for the Maker type
type MockMaker struct {
	mock.Mock
}

type MockMaker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMaker) EXPECT() *MockMaker_Expecter {
	return &MockMaker_Expecter{mock: &_m.Mock}
}

// CreateToken provides a mock function with given fields: payload
func (_m *MockMaker) CreateToken(payload Payload) (string, time.Time, error) {
	ret := _m.Called(payload)

	var r0 string
	var r1 time.Time
	var r2 error
	if rf, ok := ret.Get(0).(func(Payload) (string, time.Time, error)); ok {
		return rf(payload)
	}
	if rf, ok := ret.Get(0).(func(Payload) string); ok {
		r0 = rf(payload)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(Payload) time.Time); ok {
		r1 = rf(payload)
	} else {
		r1 = ret.Get(1).(time.Time)
	}

	if rf, ok := ret.Get(2).(func(Payload) error); ok {
		r2 = rf(payload)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockMaker_CreateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateToken'
type MockMaker_CreateToken_Call struct {
	*mock.Call
}

// CreateToken is a helper method to define mock.On call
//   - payload Payload
func (_e *MockMaker_Expecter) CreateToken(payload interface{}) *MockMaker_CreateToken_Call {
	return &MockMaker_CreateToken_Call{Call: _e.mock.On("CreateToken", payload)}
}

func (_c *MockMaker_CreateToken_Call) Run(run func(payload Payload)) *MockMaker_CreateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(Payload))
	})
	return _c
}

func (_c *MockMaker_CreateToken_Call) Return(_a0 string, _a1 time.Time, _a2 error) *MockMaker_CreateToken_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockMaker_CreateToken_Call) RunAndReturn(run func(Payload) (string, time.Time, error)) *MockMaker_CreateToken_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyToken provides a mock function with given fields: token
func (_m *MockMaker) VerifyToken(token string) (Payload, error) {
	ret := _m.Called(token)

	var r0 Payload
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (Payload, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) Payload); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Get(0).(Payload)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMaker_VerifyToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyToken'
type MockMaker_VerifyToken_Call struct {
	*mock.Call
}

// VerifyToken is a helper method to define mock.On call
//   - token string
func (_e *MockMaker_Expecter) VerifyToken(token interface{}) *MockMaker_VerifyToken_Call {
	return &MockMaker_VerifyToken_Call{Call: _e.mock.On("VerifyToken", token)}
}

func (_c *MockMaker_VerifyToken_Call) Run(run func(token string)) *MockMaker_VerifyToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockMaker_VerifyToken_Call) Return(_a0 Payload, _a1 error) *MockMaker_VerifyToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMaker_VerifyToken_Call) RunAndReturn(run func(string) (Payload, error)) *MockMaker_VerifyToken_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockMaker interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockMaker creates a new instance of MockMaker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockMaker(t mockConstructorTestingTNewMockMaker) *MockMaker {
	mock := &MockMaker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
